### ISSUE TITLE
Tensorflow 1.15.4 is not compatible with python 3.6

### ISSUE THREAD

**Issue by sophiastl97** [Mysteriousplayer/20210106#2]
Hi. In the requirements.txt file it has mentioned that we need to install Python version 3.6.13 and TensorFlow version 1.15.4 to run the project. I have installed Python 3.6, but facing an error while installing TensorFlow, which says that this version of Python is not compatible with TensorFlow. Which versions I should install that are compatible with each other?
- Additionally, it seems that the file has expired in the features link.

**Comment by Mysteriousplayer** [comment]
Package                 Version
----------------------- --------------
absl-py                 1.0.0
astor                   0.8.1
cached-property         1.5.2
certifi                 2020.6.20
cloudpickle             2.0.0
dataclasses             0.8
gast                    0.2.2
google-pasta            0.2.0
grpcio                  1.44.0
h5py                    3.1.0
importlib-metadata      4.8.3
Keras-Applications      1.0.8
Keras-Preprocessing     1.1.2
Markdown                3.3.6
numpy                   1.18.5
nvidia-cublas           11.2.1.74
nvidia-cuda-cupti       11.1.69
nvidia-cuda-nvcc        11.1.74
nvidia-cuda-nvrtc       11.1.105
nvidia-cuda-runtime     11.1.74
nvidia-cudnn            8.0.4.30
nvidia-cufft            10.3.0.74
nvidia-curand           10.2.2.74
nvidia-cusolver         11.0.0.74
nvidia-cusparse         11.2.0.275
nvidia-dali-cuda110     0.27.0
nvidia-dali-nvtf-plugin 0.27.0+nv20.11
nvidia-horovod          0.20.2+nv20.11
nvidia-nccl             2.8.2
nvidia-pyindex          1.0.9
nvidia-tensorboard      1.15.0+nv20.11
nvidia-tensorflow       1.15.4+nv20.11
nvidia-tensorrt         7.2.1.6
opt-einsum              3.3.0
pip                     21.3.1
protobuf                3.19.4
psutil                  5.9.0
PyYAML                  6.0
setuptools              58.0.4
six                     1.16.0
tensorboard             1.15.0
tensorflow-determinism  0.3.0
tensorflow-estimator    1.15.1
termcolor               1.1.0
typing_extensions       4.1.1
webencodings            0.5.1
Werkzeug                2.0.3
wheel                   0.37.1
wrapt                   1.14.0
xlrd                    1.2.0
XlsxWriter              3.0.3
zipp                    3.6.0

**Comment by Mysteriousplayer** [comment]
Hi.  If it doesn't work successfully, I suggest you try tf 0.x. 

The features link has been updated. 

Hopefully the above answers are sufficient and satisfactory to your queries.

**Comment by sophiastl97** [comment]
Thanks a lot for your response.
Unfortunately, due to my current location overseas of China, I am unable to
access the Baidu website. Is there any alternative way to access it?
